export const categories = [
  {
    id: "1",
    name: "Electronics",
    image: "/electronics.jpg?height=300&width=400",
  },
  { id: "2", name: "Clothing", image: "/clothing.jpg?height=300&width=400" },
  {
    id: "3",
    name: "Home & Garden",
    image: "/home.jpg?height=300&width=400",
  },
  {
    id: "4",
    name: "Sports",
    image: "/sports.jpg?height=300&width=400",
  },
  {
    id: "5",
    name: "Beauty & Personal Care",
    image: "/beauty.jpg?height=300&width=400",
  },
  {
    id: "6",
    name: "Books",
    image: "/books.jpg?height=300&width=400",
  },
];

export const products = [
  {
    id: "1",
    name: "Smartphone",
    category: "Electronics",
    price: 699,
    image: "/smartphone.jpg?height=200&width=200",
  },
  {
    id: "2",
    name: "Laptop",
    category: "Electronics",
    price: 1299,
    image: "/laptop.jpg?height=200&width=200",
  },
  {
    id: "3",
    name: "T-shirt",
    category: "Clothing",
    price: 29,
    image: "/t-shirt.jpg?height=200&width=200",
  },
  {
    id: "4",
    name: "Jacket",
    category: "Clothing",
    price: 59,
    image: "/jacket.jpg?height=200&width=200",
  },
  {
    id: "5",
    name: "Plant Pot",
    category: "Home & Garden",
    price: 19,
    image: "/plant-pot.jpeg?height=200&width=200",
  },
  {
    id: "6",
    name: "Tennis Racket",
    category: "Sports",
    price: 50,
    image: "/tennis-racket.jpeg?height=200&width=200",
  },
  {
    id: "7",
    name: "Basket Ball",
    category: "Sports",
    price: 30,
    image: "/basketball.jpeg?height=200&width=200",
  },
  {
    id: "8",
    name: "Footbal",
    category: "Sports",
    price: 90,
    image: "/football.jpg?height=200&width=200",
  },
  {
    id: "9",
    name: "Cricket Bat",
    category: "Sports",
    price: 400,
    image: "/bat.jpg?height=200&width=200",
  },
  {
    id: "10",
    name: "Hockey",
    category: "Sports",
    price: 40,
    image: "/hockey.jpg?height=200&width=200",
  },
  {
    id: "11",
    name: "Volleyball",
    category: "Sports",
    price: 60,
    image: "/volleyball.avif?height=200&width=200",
  },
  {
    id: "12",
    name: "Baseball",
    category: "Sports",
    price: 20,
    image: "/baseball.jpeg?height=200&width=200",
  },
  {
    id: "13",
    name: "Tennis Racket",
    category: "Sports",
    price: 100,
    image: "/tennis-racket.jpeg?height=200&width=200",
  },
  {
    id: "14",
    name: "Badminton",
    category: "Sports",
    price: 15,
    image: "/badminton.jpg?height=200&width=200",
  },
  {
    id: "15",
    name: "watch",
    category: "Electronics",
    price: 400,
    image: "/watch.jpg?height=200&width=200",
  },
];
