export const categories = [
  {
    id: "1",
    name: "Electronics",
    image: "/electronics.jpg?height=300&width=400",
  },
  { id: "2", name: "Clothing", image: "/clothing.jpg?height=300&width=400" },
  {
    id: "3",
    name: "Home & Garden",
    image: "/home.jpg?height=300&width=400",
  },
  {
    id: "4",
    name: "Sports",
    image: "/sports.jpg?height=300&width=400",
  },
  {
    id: "5",
    name: "Beauty & Personal Care",
    image: "/beauty.jpg?height=300&width=400",
  },
  {
    id: "6",
    name: "Books",
    image: "/books.jpg?height=300&width=400",
  },
];

export const products = [
  {
    id: "1",
    name: "Smartphone",
    category: "Electronics",
    price: 699,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "2",
    name: "Laptop",
    category: "Electronics",
    price: 1299,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "3",
    name: "T-shirt",
    category: "Clothing",
    price: 29,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "4",
    name: "Jeans",
    category: "Clothing",
    price: 59,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "5",
    name: "Plant Pot",
    category: "Home & Garden",
    price: 19,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "6",
    name: "Tennis Racket",
    category: "Sports & Outdoors",
    price: 89,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "7",
    name: "Tennis Racket",
    category: "Sports & Outdoors",
    price: 89,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "8",
    name: "Tennis Racket",
    category: "Sports & Outdoors",
    price: 89,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "9",
    name: "Tennis Racket",
    category: "Sports & Outdoors",
    price: 89,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "10",
    name: "Tennis Racket",
    category: "Sports & Outdoors",
    price: 89,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "11",
    name: "Tennis Racket",
    category: "Sports & Outdoors",
    price: 89,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "12",
    name: "Tennis Racket",
    category: "Sports & Outdoors",
    price: 89,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "13",
    name: "Tennis Racket",
    category: "Sports & Outdoors",
    price: 89,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "14",
    name: "Tennis Racket",
    category: "Sports & Outdoors",
    price: 89,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "15",
    name: "Tennis Racket",
    category: "Sports & Outdoors",
    price: 89,
    image: "/placeholder.svg?height=200&width=200",
  },
];
